### ISSUE TITLE
Add ability to position (x, y, scale) provided image in editor

### ISSUE THREAD

**Issue by pfrend** [mosch/react-avatar-editor#108]
Use-case for this would be loading an original image in the editor with previously used crop information.
E.g. a user has uploaded an avatar - and would then like to come back later and edit their crop window, not start from scratch every time.

Not sure if I'm missing the way to do this - but couldn't find a trivial implementation.
Seems like supplying (relative?) x and y props in addition to the current scale prop would be a nice solution.

Thanks

**Comment by hu9o** [comment]
We can already pass zoom as _prop_... it would only be consistent to, as you suggest, allow passing x and y offset as well.

My take on this would be to **split the editor into two React elements** :
- a more bare-bones "inner editor" element, with many _props_ like ``x-offset``, ``y-offset``, ``scale``, ``rotation``, ``width``, ``height``, ``borderSize``, etc; and almost no _state_.
- a general "outer editor" element that contains the inner editor, and behaves much like the editor in its current state. It would take for example ``width`` and ``height`` as _props_, but manage ``x``, ``y`` and ``scale`` as internal _state_. I say "for example", because the whole point would be that it can be easily edited by the user to suit their needs.

With this setup, the outer editor would keep track of the x- and y-offset in its _state_ and pass it down as _props_ to the inner editor, but one could easily change that to the outer editor taking those as _props_ instead -- or to the outer editor only taking an initial value by _props_, which seems to fit better the aforementioned use-case.

However, this would mean adding as many handlers as there are props in the inner editor.

**Comment by mtlewis** [comment]
This one should probably be closed since you can now pass the position as a prop.

**Comment by lavaldi** [comment]
someone solved this? `position` prop doesn't work well because disable the drag.

**Comment by laurisbernhart** [comment]
@mosch 
Hi Mosch, really nice library - thank you!

We also need the ability to recrop an image.
Do you see any way of setting the initial position and enable dragging thereafter?

thank you!

**Comment by mtlewis** [comment]
Hi! In order to allow setting the initial position and also dragging, you’ll need to pass an `onPositionChange` handler which updates the position prop outside the component. Let me know how this works out for you! I can provide some more detail or a snippet when I’m in front of my laptop. Best of luck!

**Comment by laurisbernhart** [comment]
Hi @mtlewis 

I actually managed it in an really ugly way, without handling position myself afterwards..
![image](https://user-images.githubusercontent.com/10515029/54838115-25089380-4cc8-11e9-8d50-ea7718980b30.png)

**Comment by mosch** [comment]
@laurisbernhart why not add this in a good way to this library?
