### ISSUE TITLE
Anyway to resize image to avatar editor size upon select

### ISSUE THREAD

**Issue by geohuz** [mosch/react-avatar-editor#133]
For example, I would like the selected image being automatically resized to the width of Avatar editor, and automatically set height (to keep the aspect ratio)? I know there is a function: getImageScaledToCanvas(), but I'm not sure how to render the data in the react.

**Comment by hu9o** [comment]
I think you are mistaken on `getImageScaledToCanvas()`, it's meant to retrieve the final image.

To achieve what you want, I think you need to listen to `onLoadSuccess`. Then you could set the `scale` prop to (editor_width / loaded_img_width) for the width to match that of the editor—or the same with height, anyway the aspect-ratio is preserved.

Would it work ?

**Comment by mosch** [comment]
closed for no reply.

**Comment by fernandofleury** [comment]
Is it possible to resize further than the scaled canvas? I'm displaying a larger canvas because my final image will be quite smaller. This is more from a UX perspective.

I want to avoid a manual re-scale if possible (like me drawing the final image on a canvas to resize it again). Seems a bit wasteful since the library can do that already in a sense
