### ISSUE TITLE
release 8.0.0 doesn't scale correctly

### ISSUE THREAD

**Issue by SepiaGroup** [mosch/react-avatar-editor#150]
I tried release 8.0.0 but when i scaled the image smaller than the canvas size it went to the upper left corner, not centered like it did in version 7.2.0

**Comment by mtlewis** [comment]
Hi @SepiaGroup!  Sorry about this - I didn't realise that there were people setting scale to less than 1.  Looking back at 7.2.0, I notice that panning the image didn't work when the scale was less than 1 - the image was fixed in the center of the editor.  Is this what you'd expect?  

To me, if the scale is < 1 and we're therefore allowing whitespace in the resulting image, I'd expect to be able to move the image anywhere right up to the edges of the avatar (including just off the edges).

I'm just about to open a PR which fixes the scaling behaviour when scale is less than 1, and also allows panning as I've described above.

**Comment by SepiaGroup** [comment]
yes moving the the image when scaled less than 1 as you described would be perfect. 

you need to be able to scale an image less than 1 because it starts off filling the entire crop window on load and the long side is cut off and you can never get it fully inside the crop window, see my other issue https://github.com/mosch/react-avatar-editor/issues/149

i think you can fix this issue by updating this code (i only looked at this, have not tested it - line 348 on the latest release)

```
if (canvasRatio > imageRatio) {
      newHeight = (this.getDimensions().height)
      newWidth = (width * (newHeight / height))
    } else {
      newWidth = (this.getDimensions().width)
      newHeight = (height * (newWidth / width))
}
```

if you had a flag like "fillToCrop" and then switched the height/width i "think" it would load correctly. 

otherwise very nice component - thanks.

**Comment by mtlewis** [comment]
@SepiaGroup I agree - great component.  I'm not the maintainer though - just a contributor.  Jumping in because it was my changes which caused the change in scaling behaviour from 7.x -> 8.

See my PR #152 which fixes this issue for you.

**Comment by mosch** [comment]
release 8.0.1
