### ISSUE TITLE
When converting to .toDataUrl or .toBlob - Error: Tainted canvases may not be exported.

### ISSUE THREAD

**Issue by Andriy-Kulak** [mosch/react-avatar-editor#168]
I am curious, when I try to save cropped result into something other than a canvas, I get the following error:
> SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Does anyone else get this error and is there a quick way to fix this? I am able to get canvas object back perfect, but when I try using ".toBlob" or ".toDataUrl" i get the error above. Below is my code.

```
    const onClickSave = () => {
      const canvas = this.editor.getImage();
      console.log('CANVAS 1', canvas);
      // returns normal canvas image


      const canvas2 = this.editor.getImage().toDataURL('image/png', 1);
      console.log('CANVAS 2', canvas2);
      // Error: Tainted canvases may not be exported.

      canvas.toBlob((blob) => {
        console.log('BLOB', blob);
        // Error: Tainted canvases may not be exported.
      });
   }
```
and my component:

```
<AvatarEditor
          image="https://s3.us-east-2.amazonaws.com/images-east-2.artpriority.io/cAbK2tM5GA"
          ref={this.setEditorRef}
          width={250}
          height={500}
          border={25}
          color={[255, 255, 255, 0.6]} // RGBA
          scale={1.2}
          rotate={0}
        />
```

**Comment by mtlewis** [comment]
This is happening because the image you're using is not being returned with appropriate CORS headers. When a non-CORS-enabled image is loaded into a canvas it can be displayed in the browser but you can't do anything that retrieves the data (e.g. call toDataURI). 

There's two ways to work around this - either add the appropriate headers to the images you're requesting, or use the cropping area information that's available on the component to handle the cropping part elsewhere (perhaps on the server).

**Comment by hu9o** [comment]
Alternatively, you could set the `crossOrigin` prop to `'anonymous'`:

| Prop | Type | Description |
| --- | --- | --- |
| crossOrigin | String | The value to use for the crossOrigin property of the image, if loaded from a non-data URL. Valid values are "anonymous" and "use-credentials". See [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) for more information. |

(from the [README.md](https://github.com/mosch/react-avatar-editor/blob/master/README.md))

**Comment by Andriy-Kulak** [comment]
@hu9o thanks for the tip! I missed this in the documentation!

**Comment by chrisknu** [comment]
If using firebase as hosting, this link was helpful to add the CORS headers to get past this issue:
http://stackoverflow.com/questions/37760695/firebase-storage-and-access-control-allow-origin

**Comment by elitan** [comment]
@chrisknu What CORS headers did you set on your image in Firebase Storage?

**Comment by dongapplyboard** [comment]
<img width="1348" alt="49473474-30e74d00-f7e0-11e8-83bb-718faf82d1cc" src="https://user-images.githubusercontent.com/31410257/50319912-cac52000-0497-11e9-93ef-622aae7dc312.png">

Just to follow up on this, is this because the image being loaded into canvas is from a different URL (eg. cloudfront) than our host site?

**Comment by Xulww** [comment]
> Alternatively, you could set the `crossOrigin` prop to `'anonymous'`:
> 
> Prop	Type	Description
> crossOrigin	String	The value to use for the crossOrigin property of the image, if loaded from a non-data URL. Valid values are "anonymous" and "use-credentials". See [this page](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes) for more information.
> (from the [README.md](https://github.com/mosch/react-avatar-editor/blob/master/README.md))

Use it in the AvatarEditor component
