### ISSUE TITLE
Improve image downsizing quality

### ISSUE THREAD

**Issue by exciton** [mosch/react-avatar-editor#200]
The default canvas image scaling is fairly low quality, as per this discussion: https://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality

This can be cheaply improved using imageSmoothingQuality = 'high' (see here: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality)

Or an image resizing library/method could be used that is more consistent across browsers, maybe one of these examples:
https://www.npmjs.com/package/pica
https://codepen.io/greypants/details/bmyKo

**Comment by exciton** [comment]
This might be even better - only a few k:
https://github.com/viliusle/Hermite-resize

**Comment by mosch** [comment]
imageSmoothingQuality seems like an easy fix, let's do that.

**Comment by ecjs** [comment]
I was going to submit a simple PR that fixes this issue with imageSmoothingQuality = 'high', but the quality improvement is really low, IMO.  You can attempt yourselves, maybe I implemented wrong?

The Hermite-resize looks like it might work better, although more complicated to implement.

I'm experiencing pretty bad image quality regardless of scaling:
https://www.dropbox.com/s/tsimdt1raeurdvl/Screenshot%202017-11-01%2017.11.07.png?dl=0

BTW this is with imageSmoothingQuality set as high ^^^

**Comment by ffischetti** [comment]
I've been facing this issue as well, but don't believe a PR is necessary.  

I believe the issue is that the, by default, avatar editor takes its _style_ height & width from the canvas height & width props by default.  However, we can pass those in separately via the style prop (e.g. `style={{  width: '200px, height: '100px' }}`.  

That allowed me to set the DOM size of the canvas via the height/width props and, separately, set the displayed height width via the css style prop.  To get a higher resolution image, I just have to choose a canvas DOM size is larger than the canvas css size (and large enough to generate the image quality I want).  

I get HTML that looks something like: 
`<canvas width="1250" height="725" style="width: 350px; height: 196.875px;"></canvas>`

The cropped image then draws its data from from the canvas height/width, not the smaller css.

The distinction is discussed here: https://stackoverflow.com/questions/14488849/higher-dpi-graphics-with-html5-canvas

**Comment by levivoelz** [comment]
@exciton, the other option would be to implement GameAlchemist's solution (from [SO](https://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality)), which I've done in a personal project. It does a good job of downsizing and retaining quality, but a bit of a memory hog. I modified his solution a bit to allow for transparency. I could help implement it here if you guys want.

**Comment by rhapsodyv** [comment]
Anyone working on this?

**Comment by mosch** [comment]
There is a nice list of techniques. I'm planning to work on these in the next days if I can find some time: 
https://github.com/mosch/react-avatar-editor/issues/239

**Comment by innoist** [comment]
@mosch just hit by this today.... looking forward to an early fix 👍

**Comment by sseppola** [comment]
@ffischetti what issues were you facing, and did you manage to resolve them? I'll be following in your footsteps trying to implement the same solution, would appreciate any and all tips

**Comment by ffischetti** [comment]
@sseppola I wound up doing as I posted, with good results.

I set the canvas to the size of the desired image capture.  Then I set the style on the div rendering the canvas to my desired css.  It captures an image tied to the canvas dimensions and renders the appropriate UI.  

The cropping overlay might start to look a little strange at resolutions higher than 1200 x 1200, but I haven't thoroughly tested that.  Hope that helps!

**Comment by evangow** [comment]
I'm using pica to create higher quality down-sized images. It's fairly simple to implement. The below function returns a blob URL. Alternatively, you could also just upload the blob directly to your server.

```javascript
const pica = require("pica")();

handleCreatePreview = async () => {
    const img = this.editor.getImage();
    var offScreenCanvas = document.createElement("canvas");
    offScreenCanvas.width = 1500;
    offScreenCanvas.height = 500;

    const picaCanvas = await pica.resize(img, offScreenCanvas);
    picaCanvas.toBlob(blob => 
      { return URL.createObjectURL(blob) },
      "image/jpeg",
      0.9
    )
  };
```

**Comment by sachyyn** [comment]
Is there a fix to this apart from using pica?
