### ISSUE TITLE
Position change is {x: NaN, y: NaN}

### ISSUE THREAD

**Issue by cbarraford** [mosch/react-avatar-editor#292]
I'm trying to give this package a try and can't seem to get `onPositionChange` to work properly. Whenever I drag the image, the input/param to `onPositionChange` gets `{x: NaN, y:NaN}`.

I've set up a reproducible environment to check out and see what I'm doing wrong. If you try dragging the image, and look in the console, you'll see what I mean. Thanks in advance!
https://codesandbox.io/s/182wr3nz83?fontsize=14

**Comment by cbarraford** [comment]
I've also tried re-creating the demo/docs in codesandbox.io and still couldn't get it to work. https://codesandbox.io/s/ywx32nz40z?fontsize=14

**Comment by cbarraford** [comment]
Finally figured out the problem, which was hard to find....

I was importing wrong apparently,

**Wrong**
```js
import AvatarEditor from 'react-avatar-editor'
```

**Correct**
```js
import ReactAvatarEditor from 'react-avatar-editor'
```

**Comment by mtlewis** [comment]
Hi @cbarraford. This component doesn't depend in any way on the name you use to import the component, so I suspect the problem must have been something else. I tested both the codesandbox.io links you sent - the position info is getting sent for me in both cases. Are either of them still broken for you? If not I'd love to see a broken version so I can try to understand what the problem was!

**Comment by cbarraford** [comment]
@mtlewis yeah, i would agree, something else is the issue, and I figured out what it was. I had typo'ed the `defaultProps` on line 63. I've recreated the problem again here, https://codesandbox.io/s/182wr3nz83?fontsize=14. So not an issue of the npm package, just me being stupid.

**Comment by mtlewis** [comment]
Ah, what a tricky typo! Glad you got to the bottom of it, thanks for letting me know :)
