### ISSUE TITLE
Doesn't work with SVG files in Firefox, Chrome works

### ISSUE THREAD

**Issue by ladislavjacho** [mosch/react-avatar-editor#306]
SVG are not visible in cropper in Firefox (68.0.2 64 bit). Chrome (Version 76.0.3809.132 (Official Build) (64-bit)) works.

**Comment by mosch** [comment]
Thanks for creating this issue @ladislavjacho – [according to this post on stackoverflow](https://stackoverflow.com/questions/28690643/firefox-error-rendering-an-svg-image-to-html5-canvas-with-drawimage) this is a bug in firefox when the svg doesn't have a proper size defined.
While I can see that some might want to use SVG as a profile image, I consider this as a very edge-case. And because the fix will add a lot of complexity, I'm sorry to say I don't think this will be fixed here.
