### ISSUE TITLE
result image size 5x bigger than the actual size.

### ISSUE THREAD

**Issue by pratik-walkhade** [mosch/react-avatar-editor#342]
Hi,

I am using the editor to crop the profile images but I observed the size of image which I am getting as result is almost 5x bigger than the actual image. I.e. If I am selecting an image .jpg file of 500KB and after editing it I 'll get the image of size 2.5 - 3 MB. which is too big. 
Can you please help me out.

Thanks & regards,
Pratik W.

**Comment by neemchand** [comment]
I am also facing the same problem. Did you found any solution to your problem ?

**Comment by corpsyal** [comment]
I am also facing the same problem :(

**Comment by MrHus** [comment]
I'm using pica https://github.com/nodeca/pica to reduce the size.

https://github.com/42BV/ui/blob/master/src/form/ImageUpload/ImageUpload.tsx

https://42bv.github.io/ui/storybook/?path=/story/form-imageupload--rect

**Comment by neemchand** [comment]
I handled this by writing a custom function for resizing the image before uploading. Its working fine for me. 
   
```
const handleResize = (canvas,  { cropperWidth, cropperHeight, scale = 1 } ) => {
    const offScreenCanvas = document.createElement('canvas');
    const width = cropperWidth * scale;
    const height = cropperHeight * scale;
    offScreenCanvas.width = width;
    offScreenCanvas.height = height;
    offScreenCanvas.getContext('2d').drawImage(canvas, 0, 0, width, height);
    return offScreenCanvas.toDataURL('image/png', 0.9);
  };

```

**Comment by tomasdivito** [comment]
Hi!

It was brought to my attention that in our app where we were using this library, we were having the same issue, I saw that we were retrieving the image using `getImageScaledToCanvas` and after using `getImage` instead I didn't have this issue, have you tried it?

**Comment by tomasdivito** [comment]
@mycolaos Actually, after changing the version of react-avatar-editor for an older one (for other bug) `getImageScaledToCanvas` worked correctly and didn't modified the final image size based on zoom (I wanted to keep the same size of the image based on zoom for consistency across the images uploaded by users)
We are using `"react-avatar-editor": "11.1.0"`

**Comment by mycolaos** [comment]
Not sure what do you mean. If you use `getImageScaledToCanvas` you save the zoomed part of the image only, don't you? So, it can't be possibly be the same size.

However, as I said, it depends on the format, just try saving in `image/png` and in `image/jpeg`, PNG would be bigger, JPEG may be even lower than original if it was PNG. The difference in size depends on both source and target formats.

The topic starter didn't provide enough details, but _maybe_ his problem was reading a JPEG and saving it as PNG. So for anyone who faces the size problem, check the formats as well. Obviously consider also that the quality of pictures can vary depending on the format.

**Comment by tomasdivito** [comment]
@mycolaos What I mean is, if I set the canvas to be 800height and 600width the final image, no matter how zoomed or not, the final image will be scaled to that size (which is, in my case, what I want, because I cannot upload images smaller that said size, so If you upload a an 800h600w image and you want to cut a part of the image, I want to keep it scaled as every image uploaded on the page. 

And then, format wise, yes, I imagine that the formats are important on the final size, I end up with always a jpeg image from the `getImageScaledToCanvas`, but I think there's another problem related to other version where you would end up with a much bigger than the original size no matter the end format you choose, but honestly I didn't make any test to show it up and can talk only on what I've been doing in my use case.

**Comment by mortoni** [comment]
Any solution for this?
