### ISSUE TITLE
CORS errors in Chrome with console closed

### ISSUE THREAD

**Issue by smarcet** [mosch/react-avatar-editor#354]
i am facing some issues when i try to load an image from external source (CORS).
server has set properly CORS headers, but its failing with 
Access to image at 'https://object-storage.public.mtl1.vexxhost.net/swift/v1/6e4619c416ff4bd19e1c087f27a43eea/idp-fn/profile_pics/Clint-Espinoza-2013.jpg' from origin '<ORIGIN>' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
if i try the request with the dev tools opened its does work ok.

regards

**Comment by metamorfoso** [comment]
I'm facing the same issue. 

I've yet to solve anything, but to your point:

>  if i try the request with the dev tools opened its does work ok.

I found this was the case because I had checked `Disable cache` in my dev tools.

The discussion in issue #268 suggests it might be related to browser caching and/or CORS header configuration on the server (where your asset is stored). 

You might find reading through the issue helpful as I did. In any case, hope being able to reproduce it locally was helpful to me, so I hope it helps you too.
